### ISSUE TITLE
How to get windows.lib file ?

### ISSUE THREAD

**Issue by soarway** [zerotier/DesktopUI#28] opened 2022-03-05 14:24 UTC
make[1]: Leaving directory 'D:/DesktopUI-1.8.4/tray'
cargo build --release --target=x86_64-pc-windows-msvc
error: failed to calculate checksum of: D:\DesktopUI-1.8.4\vendor\windows_x86_64_msvc\lib/windows.lib

Caused by:
  failed to open file `D:\DesktopUI-1.8.4\vendor\windows_x86_64_msvc\lib/windows.lib`

**Comment by glimberg** [comment] 2022-03-16 00:37
Duplicate of https://github.com/zerotier/DesktopUI/issues/31

**Closed by glimberg** 2022-03-16 00:37 UTC
